site_name: Learn Python
site_url: https://coreairesearch.github.io/learnai/
site_description: Learn important Python concepts hands-on by writing Python code.

repo_url: https://github.com/coreairesearch/learnai
repo_name: coreairesearch/learnai

theme:
  name: material
  # logo: assets/logo.png
  # favicon: assets/logo.png
  features:
    - navigation.instant  
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - search

edit_uri: ""

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY


# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Installation: getting-started.md