site_name: Learn AI
site_url: https://coreairesearch.github.io/learnai/
site_description: Learn important Python concepts hands-on by writing Python code.

repo_url: https://github.com/coreairesearch/learnai
repo_name: coreairesearch/learnai

theme:
  name: 'material'
  # logo: assets/logo.png
  # favicon: assets/logo.png
  features:
    - navigation.instant  
    - navigation.expand
    # - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking

  language: en

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: lime
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

markdown_extensions:
  - toc:
      permalink: true
  - meta
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  
plugins:
 - mkdocs-jupyter:
    include_source: True
 - blog
 - search:
    separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
 - minify:
    minify_html: true

edit_uri: ""

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.0/p5.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  - js/solar_system.js

# Page tree
nav:
  - Home: index.md
  - Pytorch & Deep Learning: 
    - Deep Learning With Pytorch/index.md
    - Role of PyTorch in Deep Learning: Deep Learning With Pytorch/part1-pytorch-role.md
  # - Math:
  #   - Math/Fundamentals of Calculus/index.md
  #   - Fundamentals of Calculus: Math/Fundamentals of Calculus/part1-fundaments-of-calculus.md
  - Getting started:
    - Installation: getting-started.md